spring:
  application:
    name: reservation-batch

  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

app:
  scheduling:
    notPickedUpReservationFixed:
      delayTime: 5000
      expirationTime: 7