spring:
  application:
    name: reservation-batch

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/reservation}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

app:
  scheduling:
    notPickedUpReservationFixed:
      delayTime: 300000
      expirationTime: 7