spring:
  application:
    name: reservation-notification

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/reservation}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${QUEUE_HOST:localhost}
    port: ${QUEUE_PORT:5672}
    username: ${QUEUE_USERNAME:admin}
    password: ${QUEUE_PASSWORD:admin}

app:
  queue:
    consumer:
      emailNotificationReservationQueue: email.notification.reservation.queue