spring:
  application:
    name: reservation-notification

  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

app:
  queue:
    consumer:
      emailNotificationReservationQueue: email.notification.reservation.queue