spring:
  application:
    name: reservation-api

  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  redis:
    host: localhost
    port: 6379
    password: admin
    timeout: 60000

app:
  queue:
    producer:
      emailNotificationReservationQueue: email.notification.reservation.queue
  reservation:
    expirationTime: 7