spring:
  application:
    name: reservation-api

  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update